# frozen_string_literal: true

require_relative 'forbidden_terms_test'
require_relative 'cli_test'
require_relative 'rules_ctl_test'
require_relative 'dsl_test'
require_relative 'validation_test'
require_relative 'providers_test'
require_relative 'provider_bindings_test'
require_relative 'apply_test'
require_relative 'datadog_apply_test'
require_relative 'manifest_schema_test'
require_relative 'telemetry_lookup_test'
require_relative 'onboarding_test'
require_relative 'reality_check_test'
require_relative 'reliability_model_test'
require_relative 'migration_report_test'
